FROM docker.io/debian:trixie-slim

RUN set -exu \
  && export DEBIAN_FRONTEND=noninteractive \
  && sed -i 's/Components: main/Components: main contrib non-free/g' \
      /etc/apt/sources.list.d/debian.sources \
  && apt-get -yq update \
  && apt-get -yq dist-upgrade \
  && apt-get -yq install \
    --no-install-recommends \
      alsa-utils \
      bind9-dnsutils \
      build-essential \
      ca-certificates \
      coreutils \
      curl \
      dbus \
      dbus-x11 \
      dbus-user-session \
      devscripts \
      equivs \
      expect-dev \
      fastfetch \
      firefox-esr \
      gettext-base \
      git \
      iproute2 \
      iputils-ping \
      jq \
      libgl1-mesa-dri \
      locales \
      make \
      mesa-utils \
      mingetty \
      nano \
      net-tools \
      openssl \
      socat \
      sudo \
      supervisor \
      task-gnome-desktop \
      tasksel \
      tzdata \
      udev \
      vim \
      wget \
      xwayland \
      xwayland-run \
      xwaylandvideobridge \
      xz-utils \
      ibus \
      yq

RUN set -exu \
  && mkdir -pv /var/log/supervisor \
  && chmod 777 /var/log/supervisor

COPY rootfs /

RUN set -exu \
  && export DEBIAN_FRONTEND=noninteractive \
  && export DEBEMAIL="pers.edwin@gmail.com" \
  && mkdir -pv /grd-build/ || true \
  && cd /grd-build/ || exit 1 \
  && wget http://deb.debian.org/debian/pool/main/g/gnome-remote-desktop/gnome-remote-desktop_48.0.orig.tar.xz --output-document=/grd-build/gnome-remote-desktop_48.0-1.orig.tar.xz \
  && wget http://deb.debian.org/debian/pool/main/g/gnome-remote-desktop/gnome-remote-desktop_48.0-1.dsc --output-document=/grd-build/gnome-remote-desktop_48.0-1.dsc \
  && wget http://deb.debian.org/debian/pool/main/g/gnome-remote-desktop/gnome-remote-desktop_48.0-1.debian.tar.xz --output-document=/grd-build/gnome-remote-desktop_48.0-1.debian.tar.xzc \
  && tar xvf gnome-remote-desktop_48.0-1.orig.tar.xz \
  && tar xvf gnome-remote-desktop_48.0-1.debian.tar.xzc \
  && ln -s gnome-remote-desktop_48.0-1.orig.tar.xz gnome-remote-desktop_48.0-1-kubevda.orig.tar.xz \
  && mv debian gnome-remote-desktop-48.0/ \
  && cd gnome-remote-desktop-48.0/ \
  && for patch in /grd-build/patches/debian/*.patch; do \
        patch -p1 --forward < $patch || true; \
      done \
  && cp /grd-build/patches/*.patch debian/patches/ \
  && $(cd debian/patches && ls *.patch) | tee debian/patches/series \
  && mk-build-deps --tool "apt-get -yq -o Debug::pkgProblemResolver=yes --no-install-recommends" -ir "/grd-build/gnome-remote-desktop-48.0/debian/control" \
  && dch --preserve --local "-kubevda-" "build with VNC support for kubevda" \
  && DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -uc -us \
  && dpkg -i /grd-build/gnome-remote-desktop_48.0-1-kubevda-1_amd64.deb \
  && dpkg -P gnome-remote-desktop-build-deps \
  && apt-get -yq clean \
  && apt-get -yq autoremove

CMD ["/bin/bash", "/entrypoint.sh"]
