FROM docker.io/debian:trixie-slim

RUN set -exu \
  && export DEBIAN_FRONTEND=noninteractive \
  && sed -i 's/Components: main/Components: main contrib non-free/g' \
      /etc/apt/sources.list.d/debian.sources \
  && apt-get -yq update \
  && apt-get -yq dist-upgrade \
  && apt-get -yq install \
    --no-install-recommends \
      alsa-utils \
      bind9-dnsutils \
      build-essential \
      ca-certificates \
      coreutils \
      curl \
      dbus \
      dbus-x11 \
      devscripts \
      equivs \
      expect-dev \
      fastfetch \
      firefox-esr \
      gettext-base \
      git \
      iproute2 \
      iputils-ping \
      jq \
      libgl1-mesa-dri \
      locales \
      make \
      mesa-utils \
      mingetty \
      nano \
      net-tools \
      openssl \
      socat \
      sudo \
      supervisor \
      task-gnome-desktop \
      tasksel \
      tzdata \
      udev \
      vim \
      wget \
      xwayland \
      xwayland-run \
      xwaylandvideobridge \
      xz-utils \
      yq

RUN set -exu \
  && mkdir -pv /var/log/supervisor \
  && chmod 777 /var/log/supervisor

COPY rootfs /

RUN set -exu \
  && export DEBIAN_FRONTEND=noninteractive \
  && export DEBEMAIL="pers.edwin@gmail.com" \
  && git clone https://salsa.debian.org/gnome-team/gnome-remote-desktop.git /gnome-remote-desktop \
  && cd /gnome-remote-desktop \
  && for patch in /gnome-remote-desktop-patches/*.patch; do \
        patch -p1 --forward < $patch || true; \
      done \
  && mk-build-deps --tool "apt-get -yq -o Debug::pkgProblemResolver=yes --no-install-recommends" -ir "/gnome-remote-desktop/debian/control" \
  && DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -uc -us \
  && dpkg -i ../gnome-remote-desktop*.deb \
  && dpkg -P gnome-remote-desktop-build-deps \
  && apt-get -yq clean \
  && apt-get -yq autoremove

CMD ["/bin/bash", "/entrypoint.sh"]
